#ifndef COMMON_HPP
#define COMMON_HPP

// This depends on the assembly generated by the compiler
#ifdef __x86_64
#define INSTRUCTION_LENGTH 8
#else
#define INSTRUCTION_LENGTH 6
#endif

// Don't care about ODR here, since this header is only included once per executable
long factorial(long a)
{
	long b = a;
	for (long i = 2; i < a; i++)
		b *= i;
	return b;
}

long sum(long a, long b)
{
	return a + b;
}

typedef long (*FactorialFunc)(long);
typedef long (*SumFunc)(long, long);


#endif